import type { DashboardData } from "./types";

export const DEMO_DATA: DashboardData = {
  kpis: {
    cantidad: 14730,
    meGusta: 12450,
    compartido: 755,
    comentario: 2267,
    seguidoresCaptados: 4750,
    ondaExpansiva: 0,
    ondaFactor: 300,
    ondaAuto: true,
    totalInvertido: 8546345,
  },
  links: [
    {
      id: "l1",
      publicacion: "Así soy, así hablo.",
      url: "https://www.instagram.com/reel/DVSWv5VDLx3/?igsh=M2JiMmRhczZjcnhu",
      medio: "Instagram",
      cantidad: 285432,
      engagementRate: 22,
    },
    {
      id: "l2",
      publicacion: "Colombia tiene talento, creatividad y una enorme fuerza cultural.",
      url: "https://www.instagram.com/reel/DVhSE0Yj6iw/?igsh=aHp6cjVkd2hnOTM%3D",
      medio: "Instagram",
      cantidad: 184534,
      engagementRate: 14,
    },
    {
      id: "l3",
      publicacion: "Manizales es talento, tradición y cultura viva.",
      url: "https://www.instagram.com/reel/DVdq6GXDpX-/?igsh=MXhsbGJodzVrbnhxNg%3D%3D&wa_logging_event=video_play_open",
      medio: "Instagram",
      cantidad: 87003,
      engagementRate: 8,
    },
    {
      id: "l4",
      publicacion: "Faltan 5 días. 💯❤️",
      url: "https://www.instagram.com/reel/DVbnylQkTHL/?igsh=Zm53N201dWdhZGFo&wa_logging_event=video_play_open",
      medio: "Instagram",
      cantidad: 65879,
      engagementRate: 11,
    },
    {
      id: "l5",
      publicacion: "¿Sabes quién es L100? ❤️💯",
      url: "https://www.instagram.com/reel/DU9WBGrj6W9/?igsh=MTRqNTgzZWwwNGxsdQ%3D%3D&wa_logging_event=video_play_open",
      medio: "Instagram",
      cantidad: 53574,
      engagementRate: 7,
    },
    {
      id: "l6",
      publicacion: "Sin cédula no hay voto y sin voto no hay cambio",
      url: "https://www.tiktok.com/@mariapazgaviria/video/7609304841868938510?_r=1&_t=ZS-94fO1LyytNc",
      medio: "TikTok",
      cantidad: 46374,
      engagementRate: 5.1,
    },
  ],
  temas: [
    { id: "t1", tema: "Territorio y comunidad", cantidad: 5510 },
    { id: "t2", tema: "Democracia", cantidad: 6450 },
    { id: "t3", tema: "Empleo Joven", cantidad: 5704 },
    { id: "t4", tema: "Salud Pública", cantidad: 2768 },
    { id: "t5", tema: "Medio Ambiente", cantidad: 1766 },
    { id: "t6", tema: "Defensa de conversación", cantidad: 2203 },
  ],
  medios: [],
  contactoDirecto: {
    diasCampana: 10,
    sms: {
      enviosDiarios: 385735,
      frecuencia: "Interdiario",
      costoUnitario: 32,
    },
    llamadas: {
      llamadasDiarias: 153789,
      frecuencia: "Interdiario",
      costoUnitario: 862,
    },
  },
  pautaMeta: [
    {
      id: "pm1",
      campana: "Reconocimiento_5Dias",
      resultados: 16091,
      tipoResultado: "Alcance",
      costoPorResultado: 989,
      importeGastado: 15906,
      impresiones: 16589,
      alcance: 16675,
    },
    {
      id: "pm2",
      campana: "Reconocimiento_Marca_L100",
      resultados: 99131,
      tipoResultado: "Alcance",
      costoPorResultado: 1058,
      importeGastado: 104888,
      impresiones: 108722,
      alcance: 104247,
    },
    {
      id: "pm3",
      campana: "Trafico_Video_SabesQuienEsL10",
      resultados: 2121,
      tipoResultado: "Visitas al perfil y a la pagina",
      costoPorResultado: 260,
      importeGastado: 551202,
      impresiones: 77173,
      alcance: 50824,
    },
    {
      id: "pm4",
      campana: "Campana de Trafico con la configuracion recomendada",
      resultados: 5153,
      tipoResultado: "Visitas al perfil de Instagram",
      costoPorResultado: 146,
      importeGastado: 752902,
      impresiones: 208918,
      alcance: 130107,
    },
    {
      id: "pm5",
      campana: "Reconocimiento_Video_L100",
      resultados: 541073,
      tipoResultado: "Alcance",
      costoPorResultado: 1561,
      importeGastado: 844812,
      impresiones: 769692,
      alcance: 541073,
    },
    {
      id: "pm6",
      campana: "Reconocimiento__Bogota_Creatividad",
      resultados: 0,
      tipoResultado: "Alcance",
      costoPorResultado: 0,
      importeGastado: 0,
      impresiones: 0,
      alcance: 0,
    },
    {
      id: "pm7",
      campana: "Reconocimiento_Armenia",
      resultados: 0,
      tipoResultado: "Alcance",
      costoPorResultado: 0,
      importeGastado: 0,
      impresiones: 0,
      alcance: 0,
    },
    {
      id: "pm8",
      campana: "Reconocimiento_Video_Falta_1mes",
      resultados: 474052,
      tipoResultado: "Alcance",
      costoPorResultado: 1444,
      importeGastado: 684474,
      impresiones: 698539,
      alcance: 474052,
    },
  ],
  conclusiones: [
    {
      id: "c1",
      texto:
        "La estrategia evidencia una fuerte capacidad de producción y circulación de contenidos, lo que permitió mantener una presencia digital constante y sostener la visibilidad de los temas estratégicos en redes sociales.",
    },
    {
      id: "c2",
      texto:
        "El alcance superior a 5,7 millones de personas demuestra una capacidad efectiva de amplificación, logrando que los mensajes trasciendan las audiencias directas y se posicionen en conversaciones digitales más amplias.",
    },
    {
      id: "c3",
      texto:
        "Instagram se consolida como el principal canal de difusión, concentrando más del 80 % de la distribución, lo que confirma la efectividad de los formatos visuales y narrativos propios de esta plataforma para amplificar los contenidos.",
    },
    {
      id: "c4",
      texto:
        "Los temas relacionados con territorio, comunidad y democracia muestran mayor capacidad de resonancia, lo que sugiere que estas narrativas generan mayor conexión con las audiencias y representan una oportunidad estratégica para fortalecer el engagement en futuras fases de la estrategia digital.",
    },
  ],
};