import type { DashboardData } from "./types";

export const DEMO_DATA: DashboardData = {
  kpis: {
    Contenidos Apoyados: 68,
    meGusInteracciones obtenidas: 50277,
    compartidos en medios: 33277,
    comentarios generados: 2643,
    seguidoresCaptados: 1546,
    ondaExpansiva: 0,
    ondaFactor: 500,
    ondaAuto: true,
    totalInvertido: 0,
  },
  Principales links Apoyados: [
    {
      id: "l1",
      publicacion: "Ser pilo paga",
      url: "https://www.facebook.com/reel/738035089100324,
      medio: "Facebook",
      cantidad: 134646,
      engagementRate: 13,
    },
    {
      id: "l2",
      publicacion: "Taxis Impagables",
      url: "https://www.facebook.com/reel/927184122988620/",
      medio: "Facebook",
      cantidad: 105468,
      engagementRate: 11,
    },
    {
      id: "l3",
      publicacion: "Renta Vida",
      url: "https://www.facebook.com/reel/1574730477106284",
      medio: "Facebook",
      cantidad: 84968,
      engagementRate: 9,
    },
    {
      id: "l4",
      publicacion: "Economía colaborativa",
      url: "https://www.facebook.com/reel/1616183669384053",
      medio: "Facebook",
      cantidad: 73896,
      engagementRate: 8,
    },
    {
      id: "l5",
      publicacion: "Sustituir el IVA",
      url: "https://www.facebook.com/reel/1593871485254454",
      medio: "Facebook",
      cantidad: 63748,
      engagementRate: 7,
    },
    {
      id: "l6",
      publicacion: "Sin cédula no hay voto y sin voto no hay cambio",
      url: "https://www.facebook.com/ChaconDialoga/posts/pfbid08aYBSY5LRd6qADEFVq1Jstm97yXdUPwy29UvEr8eASz6gjD1UNwbBdEVCuf3ERQDl?rdid=n4fUYUBmmp8VxKpM#",
      medio: "Facebook",
      cantidad: 47362,
      engagementRate: 5,
    },
  ],
  temas: [
    { id: "t1", tema: "Territorio y comunidad", cantidad: 5510 },
    { id: "t2", tema: "Democracia", cantidad: 6450 },
    { id: "t3", tema: "Empleo Joven", cantidad: 5704 },
    { id: "t4", tema: "Salud Pública", cantidad: 2768 },
    { id: "t5", tema: "Medio Ambiente", cantidad: 1766 },
    { id: "t6", tema: "Defensa de conversación", cantidad: 2203 },
  ],
  medios: [],
  contactoDirecto: {
    diasCampana: 10,
    sms: {
      enviosDiarios: 385735,
      frecuencia: "Interdiario",
      costoUnitario: 0,
    },
    llamadas: {
      llamadasDiarias: 153789,
      frecuencia: "Interdiario",
      costoUnitario: 0,
    },
  },
  pautaMeta: [
    {
      id: "pm1",
      campana: "Reconocimiento_5Dias",
      resultados: 16091,
      tipoResultado: "Alcance",
      costoPorResultado: 989,
      importeGastado: 15906,
      impresiones: 16589,
      alcance: 16675,
    },
    {
      id: "pm2",
      campana: "Reconocimiento_Marca_L100",
      resultados: 99131,
      tipoResultado: "Alcance",
      costoPorResultado: 1058,
      importeGastado: 104888,
      impresiones: 108722,
      alcance: 104247,
    },
    {
      id: "pm3",
      campana: "Trafico_Video_SabesQuienEsL10",
      resultados: 2121,
      tipoResultado: "Visitas al perfil y a la pagina",
      costoPorResultado: 260,
      importeGastado: 551202,
      impresiones: 77173,
      alcance: 50824,
    },
    {
      id: "pm4",
      campana: "Campana de Trafico con la configuracion recomendada",
      resultados: 5153,
      tipoResultado: "Visitas al perfil de Instagram",
      costoPorResultado: 146,
      importeGastado: 752902,
      impresiones: 208918,
      alcance: 130107,
    },
    {
      id: "pm5",
      campana: "Reconocimiento_Video_L100",
      resultados: 541073,
      tipoResultado: "Alcance",
      costoPorResultado: 1561,
      importeGastado: 844812,
      impresiones: 769692,
      alcance: 541073,
    },
    {
      id: "pm6",
      campana: "Reconocimiento__Bogota_Creatividad",
      resultados: 0,
      tipoResultado: "Alcance",
      costoPorResultado: 0,
      importeGastado: 0,
      impresiones: 0,
      alcance: 0,
    },
    {
      id: "pm7",
      campana: "Reconocimiento_Armenia",
      resultados: 0,
      tipoResultado: "Alcance",
      costoPorResultado: 0,
      importeGastado: 0,
      impresiones: 0,
      alcance: 0,
    },
    {
      id: "pm8",
      campana: "Reconocimiento_Video_Falta_1mes",
      resultados: 474052,
      tipoResultado: "Alcance",
      costoPorResultado: 1444,
      importeGastado: 684474,
      impresiones: 698539,
      alcance: 474052,
    },
  ],
  conclusiones: [
    {
      id: "c1",
      texto:
        "El alcance orgánico impulsado por la tropa fue altamente efectivo alcanzando 931.367 personas.",
    },
    {
      id: "c2",
      texto:
        "La campaña de contención de ataques disminuyó los ataques de bodegas en un 90%.",
    },
    {
      id: "c3",
      texto:
        " La campaña de distribución de contenido alterno posicionó la imagen del Senador en sectores apolíticos.",
    },
    {
      id: "c4",
      texto:
        "Los temas relacionados con territorio, comunidad y democracia muestran mayor capacidad de resonancia, lo que sugiere que estas narrativas generan mayor conexión con las audiencias y representan una oportunidad estratégica para fortalecer el engagement en futuras fases de la estrategia digital.",
    },
  ],
};