import type { DashboardData } from "./types";

export const DEMO_DATA: DashboardData = {
  kpis: {
    cantidad: 9.175,
    meGusta: 12.450,
    compartido: 755,
    comentario: 2.267,
    seguidoresCaptados: 4.750,
    ondaExpansiva: 0, // auto-calculated if ondaAuto
    ondaFactor: 300,
    ondaAuto: true,
    totalInvertido: 8546345,
  },
  links: [
    {
      id: "l1",
      publicacion: "Video campana cultura",
      url: "https://facebook.com/post/ejemplo-campana-2024",
      medio: "Facebook",
      cantidad: 4500,
      engagementRate: 4.5,
    },
    {
      id: "l2",
      publicacion: "Reel L100 viral",
      url: "https://tiktok.com/@marca/video/12345678",
      medio: "TikTok",
      cantidad: 12300,
      engagementRate: 8.2,
    },
    {
      id: "l3",
      publicacion: "Carrusel territorio",
      url: "https://instagram.com/p/ABCdef123/",
      medio: "Instagram",
      cantidad: 8700,
      engagementRate: 6.7,
    },
    {
      id: "l4",
      publicacion: "Hilo democracia",
      url: "https://twitter.com/marca/status/987654321",
      medio: "Twitter/X",
      cantidad: 2100,
      engagementRate: 3.2,
    },
    {
      id: "l5",
      publicacion: "Articulo comunidad",
      url: "https://linkedin.com/posts/marca-actividad-abc",
      medio: "LinkedIn",
      cantidad: 1500,
      engagementRate: 2.8,
    },
    {
      id: "l6",
      publicacion: "Documental caminantes",
      url: "https://youtube.com/watch?v=dQw4w9WgXcQ",
      medio: "YouTube",
      cantidad: 6400,
      engagementRate: 5.1,
    },
  ],
  temas: [
    { id: "t1", tema: "Reforma Educativa", cantidad: 1500000 },
    { id: "t2", tema: "Seguridad Ciudadana", cantidad: 1200000 },
    { id: "t3", tema: "Empleo Joven", cantidad: 980000 },
    { id: "t4", tema: "Salud Publica", cantidad: 750000 },
    { id: "t5", tema: "Medio Ambiente", cantidad: 420000 },
  ],
  medios: [], // auto-calculated from links by default
  contactoDirecto: {
    diasCampana: 10,
    sms: {
      enviosDiarios: 385735,
      frecuencia: "Interdiario",
      costoUnitario: 32,
    },
    llamadas: {
      llamadasDiarias: 153789,
      frecuencia: "Interdiario",
      costoUnitario: 862,
    },
  },
  pautaMeta: [
    {
      id: "pm1",
      campana: "Reconocimiento_5Dias",
      resultados: 16091,
      tipoResultado: "Alcance",
      costoPorResultado: 989,
      importeGastado: 15906,
      impresiones: 16589,
      alcance: 16675,
    },
    {
      id: "pm2",
      campana: "Reconocimiento_Marca_L100",
      resultados: 99131,
      tipoResultado: "Alcance",
      costoPorResultado: 1058,
      importeGastado: 104888,
      impresiones: 108722,
      alcance: 104247,
    },
    {
      id: "pm3",
      campana: "Trafico_Video_SabesQuienEsL10",
      resultados: 2121,
      tipoResultado: "Visitas al perfil y a la pagina",
      costoPorResultado: 260,
      importeGastado: 551202,
      impresiones: 77173,
      alcance: 50824,
    },
    {
      id: "pm4",
      campana: "Campana de Trafico con la configuracion recomendada",
      resultados: 5153,
      tipoResultado: "Visitas al perfil de Instagram",
      costoPorResultado: 146,
      importeGastado: 752902,
      impresiones: 208918,
      alcance: 130107,
    },
    {
      id: "pm5",
      campana: "Reconocimiento_Video_L100",
      resultados: 541073,
      tipoResultado: "Alcance",
      costoPorResultado: 1561,
      importeGastado: 844812,
      impresiones: 769692,
      alcance: 541073,
    },
    {
      id: "pm6",
      campana: "Reconocimiento__Bogota_Creatividad",
      resultados: 0,
      tipoResultado: "Alcance",
      costoPorResultado: 0,
      importeGastado: 0,
      impresiones: 0,
      alcance: 0,
    },
    {
      id: "pm7",
      campana: "Reconocimiento_Armenia",
      resultados: 0,
      tipoResultado: "Alcance",
      costoPorResultado: 0,
      importeGastado: 0,
      impresiones: 0,
      alcance: 0,
    },
    {
      id: "pm8",
      campana: "Reconocimiento_Video_Falta_1mes",
      resultados: 474052,
      tipoResultado: "Alcance",
      costoPorResultado: 1444,
      importeGastado: 684474,
      impresiones: 698539,
      alcance: 474052,
    },
  ],
  conclusiones: [
    { id: "c1", texto: "La campana de reconocimiento en video tuvo el mayor alcance con mas de 500,000 personas alcanzadas." },
    { id: "c2", texto: "TikTok presenta el engagement rate mas alto (8.2%), seguido de Instagram (6.7%)." },
    { id: "c3", texto: "El contacto directo via SMS y llamadas permite llegar a segmentos sin acceso a redes sociales." },
  ],
};
